// Code generated by "stringer -type=MessageType -trimprefix=Msg"; DO NOT EDIT.

package dhcp

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MsgDiscover-1]
	_ = x[MsgOffer-2]
	_ = x[MsgRequest-3]
	_ = x[MsgDecline-4]
	_ = x[MsgAck-5]
	_ = x[MsgNak-6]
	_ = x[MsgRelease-7]
	_ = x[MsgInform-8]
}

const _MessageType_name = "DiscoverOfferRequestDeclineAckNakReleaseInform"

var _MessageType_index = [...]uint8{0, 8, 13, 20, 27, 30, 33, 40, 46}

func (i MessageType) String() string {
	i -= 1
	if i >= MessageType(len(_MessageType_index)-1) {
		return "MessageType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _MessageType_name[_MessageType_index[i]:_MessageType_index[i+1]]
}
